/Users/wzheng/opt/anaconda3/lib/python3.9/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():
Traceback (most recent call last):
  File "/Users/wzheng/Desktop/train/work/07/d13e087ab16a49c460ce17410fb8b8/.command.sh", line 86, in <module>
    main()
  File "/Users/wzheng/Desktop/train/work/07/d13e087ab16a49c460ce17410fb8b8/.command.sh", line 84, in main
    illumina_sample_sheet('Library_QC_and_pooling.xlsx', 'UD.Index\ Plates\\A\\-\\D.xlsx', 'samplesheet_demux.csv', 'EXP200230012')
  File "/Users/wzheng/Desktop/train/work/07/d13e087ab16a49c460ce17410fb8b8/.command.sh", line 45, in illumina_sample_sheet
    df2 = pd.read_excel(indexs, skiprows=2, sheet_name = 'Plate D')
  File "/Users/wzheng/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/wzheng/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 457, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/Users/wzheng/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1376, in __init__
    ext = inspect_excel_format(
  File "/Users/wzheng/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1250, in inspect_excel_format
    with get_handle(
  File "/Users/wzheng/opt/anaconda3/lib/python3.9/site-packages/pandas/io/common.py", line 798, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'UD.Index\\ Plates\\A\\-\\D.xlsx'
